import { runtime, expose } from "./shared.js";

function renderGameToText() {
  const points = runtime.polygonPoints();
  const point = runtime.pointPosition();
  const corePoint = runtime.vertexPoint(0);
  const verticesExact = runtime.currentExactIntegerState(runtime.state, "verticesExact", "vertices", 3n);
  const speedLevelExact = runtime.currentExactIntegerState(runtime.state, "speedLevelExact", "speedLevel");
  const gainLevelExact = runtime.currentExactIntegerState(runtime.state, "gainLevelExact", "gainLevel");
  const infinityCountExact = runtime.currentExactIntegerState(runtime.state, "infinityCountExact", "infinityCount");
  const eternityCountExact = runtime.currentExactIntegerState(runtime.state, "eternityCountExact", "eternityCount");
  const scoreLog = runtime.currentScoreLog10();
  const finalGainLog = runtime.finalScoreGainLog10();
  const totalScoreLog = runtime.currentTotalScoreLog10();
  const generationScoreLog = runtime.currentGenerationScoreLog10();
  const infinityPointsLog = runtime.currentInfinityPointsLog10();
  const infinityPointGain = runtime.infinityPointGain();
  const infinityPointGainLog10 = runtime.infinityPointGainLog10();
  const infiniteScoreLog = runtime.currentInfiniteScoreLog10();
  const infiniteAngleBoostLog10 = runtime.infiniteAngleBoostLog10();
  const infiniteAngleCostLogs = {
    speed: runtime.infiniteAngleUpgradeCostLog10("speed"),
    vertex: runtime.infiniteAngleUpgradeCostLog10("vertex"),
    gain: runtime.infiniteAngleUpgradeCostLog10("gain"),
  };
  const currentGainLog = runtime.currentGainLog10();
  const currentCostLogs = runtime.costLogs();
  const gainExpression = runtime.gainExpressionConfig();
  const eternityGainLog10 = runtime.eternityGainLog10();
  const timelineEternityRequirement = runtime.timelineEternityRequirement();
  return JSON.stringify({
    coordinateSystem: "canvas pixels, origin top-left, x right, y down",
    score: runtime.scoreDisplay(),
    scoreLog10: Number.isFinite(scoreLog) ? Number(scoreLog.toPrecision(6)) : null,
    totalScore: runtime.formatHeldUiLogNumber(totalScoreLog),
    totalScoreLog10: Number.isFinite(totalScoreLog) ? Number(totalScoreLog.toPrecision(6)) : null,
    generationScore: runtime.formatHeldUiLogNumber(generationScoreLog),
    generationScoreLog10: Number.isFinite(generationScoreLog) ? Number(generationScoreLog.toPrecision(6)) : null,
    currentGain: runtime.formatUiLogNumber(currentGainLog),
    currentGainLog10: Number.isFinite(currentGainLog) ? Number(currentGainLog.toPrecision(6)) : null,
    finalGainOnCore: runtime.formatUiLogNumber(finalGainLog),
    finalGainOnCoreLog10: Number.isFinite(finalGainLog) ? Number(finalGainLog.toPrecision(6)) : null,
    baseGainExpression: runtime.formatGainExpressionSummary(),
    baseGainExpressionDivisor: gainExpression.divisor,
    baseGainExpressionParts: gainExpression.parts,
    vertices: runtime.effectiveVertexCount(),
    verticesExact: verticesExact.toString(),
    lapSeconds: Number(runtime.lapDuration().toPrecision(6)),
    lapSpeedMultiplier: Number(runtime.lapSpeedMultiplier().toPrecision(6)),
    lapSpeedLog10: Number(runtime.effectiveLapSpeedLog10().toPrecision(6)),
    rawLapSpeedMultiplier: runtime.valueFromLog10(runtime.rawLapSpeedLog10()),
    rawLapSpeedLog10: Number(runtime.rawLapSpeedLog10().toPrecision(6)),
    lapSpeedSoftcapStart: Number(runtime.lapSpeedSoftcapStart().toPrecision(6)),
    lapSpeedSoftcapPower: Number(runtime.lapSpeedSoftcapPower().toPrecision(6)),
    lapSpeedSoftcapped: runtime.isLapSpeedSoftcapped(),
    point: { x: Number(point.x.toFixed(1)), y: Number(point.y.toFixed(1)), progress: Number(runtime.state.pointProgress.toFixed(3)) },
    core: { x: Number(corePoint.x.toFixed(1)), y: Number(corePoint.y.toFixed(1)) },
    coreCount: runtime.coreVertexIndices().length,
    upgrades: {
      speedLevel: runtime.state.speedLevel,
      speedLevelExact: speedLevelExact.toString(),
      gainLevel: runtime.state.gainLevel,
      gainLevelExact: gainLevelExact.toString(),
      costs: {
        speed: runtime.formatUiLogNumber(currentCostLogs.speed),
        speedLog10: Number(currentCostLogs.speed.toPrecision(6)),
        vertex: runtime.formatUiLogNumber(currentCostLogs.vertex),
        vertexLog10: Number(currentCostLogs.vertex.toPrecision(6)),
        gain: runtime.formatUiLogNumber(currentCostLogs.gain),
        gainLog10: Number(currentCostLogs.gain.toPrecision(6)),
      },
    },
    generation: {
      unlocked: runtime.currentTotalScoreLog10() >= runtime.log10Value(runtime.GENERATION_UNLOCK_SCORE),
      canGenerate: runtime.canRunGeneration(),
      requirement: runtime.formatUiLogNumber(runtime.generationRequirementLog10()),
      requirementLog10: Number(runtime.generationRequirementLog10().toPrecision(6)),
      count: runtime.state.generationCount,
      previousGenerationScore: runtime.formatUiLogNumber(runtime.currentPreviousGenerationScoreLog10()),
      previousGenerationScoreLog10: Number.isFinite(runtime.currentPreviousGenerationScoreLog10()) ? Number(runtime.currentPreviousGenerationScoreLog10().toPrecision(6)) : null,
      rawScoreMultiplier: runtime.formatUiLogNumber(runtime.currentGenerationScoreMultiplierLog10()),
      rawScoreMultiplierLog10: Number(runtime.currentGenerationScoreMultiplierLog10().toPrecision(6)),
      achievementScoreMultiplier: runtime.formatUiLogNumber(runtime.generationScoreMultiplierBaseEffectLog10()),
      scoreMultiplier: runtime.formatUiLogNumber(runtime.generationScoreMultiplierEffectLog10()),
      scoreMultiplierLog10: Number(runtime.generationScoreMultiplierEffectLog10().toPrecision(6)),
      costFactor: Number(runtime.generationCostFactorEffect().toFixed(2)),
    },
    coreBoost: {
      canBoost: runtime.canCoreBoost(),
      count: runtime.state.coreBoostCount,
      requirement: runtime.formatPowerOfTen(runtime.coreBoostRequirementLog10()),
      requirementLog10: runtime.coreBoostRequirementLog10(),
      requirementText: runtime.formatPowerOfTen(runtime.coreBoostRequirementLog10()),
      requirementGrowthPowerRaw: runtime.coreBoostRequirementRawGrowthPower(),
      requirementGrowthPower: runtime.coreBoostRequirementGrowthPower(),
      gainIncreaseMultiplier: Number(runtime.coreBoostGainIncreaseMultiplier().toFixed(2)),
      gainExponent: Number(runtime.coreBoostGainExponent().toFixed(2)),
    },
    infinity: {
      canInfinity: runtime.canInfinity(),
      count: runtime.state.infinityCount,
      countExact: infinityCountExact.toString(),
      points: runtime.formatHeldUiLogNumber(infinityPointsLog, runtime.state.infinityPointsExact),
      pointsLog10: Number.isFinite(infinityPointsLog) ? Number(infinityPointsLog.toPrecision(6)) : null,
      pointGain: infinityPointGainLog10 > runtime.log10Value(Number.MAX_VALUE)
        ? runtime.formatUiLogNumber(infinityPointGainLog10)
        : infinityPointGain,
      pointGainLog10: Number.isFinite(infinityPointGainLog10) ? Number(infinityPointGainLog10.toPrecision(6)) : null,
      infiniteScore: runtime.formatHeldUiLogNumber(infiniteScoreLog),
      infiniteScoreLog10: Number.isFinite(infiniteScoreLog) ? Number(infiniteScoreLog.toPrecision(6)) : null,
      infiniteAngleBoost: Number(runtime.infiniteAngleBoost().toFixed(2)),
      infiniteAngleBoostLog10: Number.isFinite(infiniteAngleBoostLog10) ? Number(infiniteAngleBoostLog10.toPrecision(6)) : null,
      infiniteAngle: {
        unlocked: runtime.state.infiniteAngleUnlocked,
        score: runtime.formatHeldUiLogNumber(infiniteScoreLog),
        scoreLog10: Number.isFinite(infiniteScoreLog) ? Number(infiniteScoreLog.toPrecision(6)) : null,
        boost: Number(runtime.infiniteAngleBoost().toPrecision(6)),
        boostLog10: Number.isFinite(infiniteAngleBoostLog10) ? Number(infiniteAngleBoostLog10.toPrecision(6)) : null,
        vertices: runtime.infiniteAngleVertexCount(),
        purchasedSpeedLevel: runtime.infiniteAnglePurchasedUpgradeLevel("speed"),
        purchasedVertexLevel: runtime.infiniteAnglePurchasedUpgradeLevel("vertex"),
        purchasedGainLevel: runtime.infiniteAnglePurchasedUpgradeLevel("gain"),
        freeSpeedLevel: runtime.infiniteAngleFreeUpgradeLevel("speed"),
        freeVertexLevel: runtime.infiniteAngleFreeUpgradeLevel("vertex"),
        freeGainLevel: runtime.infiniteAngleFreeUpgradeLevel("gain"),
        speedLevel: runtime.infiniteAngleEffectiveUpgradeLevel("speed"),
        vertexLevel: runtime.infiniteAngleEffectiveUpgradeLevel("vertex"),
        gainLevel: runtime.infiniteAngleEffectiveUpgradeLevel("gain"),
        currentGain: runtime.formatUiLogNumber(runtime.infiniteAngleCurrentGainLog10()),
        currentGainLog10: Number(runtime.infiniteAngleCurrentGainLog10().toPrecision(6)),
        lapSeconds: Number(runtime.infiniteAngleLapDuration().toPrecision(6)),
        costs: {
          speed: runtime.formatUiLogNumber(infiniteAngleCostLogs.speed),
          vertex: runtime.formatUiLogNumber(infiniteAngleCostLogs.vertex),
          gain: runtime.formatUiLogNumber(infiniteAngleCostLogs.gain),
          speedLog10: Number(infiniteAngleCostLogs.speed.toPrecision(6)),
          vertexLog10: Number(infiniteAngleCostLogs.vertex.toPrecision(6)),
          gainLog10: Number(infiniteAngleCostLogs.gain.toPrecision(6)),
        },
      },
      activeChallenge: runtime.state.activeChallenge,
      completedChallenges: runtime.completedChallengeCount(),
      challengeCount: runtime.INFINITY_CHALLENGE_COUNT,
      challengesUnlocked: runtime.infinityChallengesUnlocked(),
      activeChallengeName: runtime.state.activeChallenge > 0 ? runtime.challengeName(runtime.state.activeChallenge) : runtime.challengeName(0),
      softcapPower: Number(runtime.infinitySoftcapPower().toFixed(3)),
      capBroken: runtime.state.infiniteCapBroken,
      canBreakCap: runtime.canBreakInfiniteCap(),
      infiniteAngleUnlockCostLog10: runtime.INFINITE_ANGLE_UNLOCK_COST_LOG10,
      selectedUpgrade: runtime.selectedInfinityUpgradeId,
      selectedUpgradeCanBuy: runtime.canBuyInfinityUpgrade(runtime.selectedInfinityUpgradeId),
      upgrades: runtime.INFINITY_UPGRADES.map((upgrade) => ({
        id: upgrade.id,
        purchased: runtime.hasInfinityUpgrade(upgrade.id),
        canBuy: runtime.canBuyInfinityUpgrade(upgrade.id),
      })),
    },
    eternity: {
      count: runtime.state.eternityCount,
      countExact: eternityCountExact.toString(),
      canEternity: runtime.canEternity(),
      pendingGain: runtime.formatUiLogNumber(eternityGainLog10),
      pendingGainLog10: Number.isFinite(eternityGainLog10) ? Number(eternityGainLog10.toPrecision(6)) : null,
    },
    tower: {
      floor: runtime.towerFloor(),
      scoreExponent: Number(runtime.towerScoreExponent().toFixed(4)),
      challenge1ScorePowerBase: runtime.hasInfinityUpgrade("13-1") ? 0.5 : runtime.INFINITE_ANGLE_SCORE_POWER,
      challenge1ScorePowerBonus: runtime.towerChallenge1InfinityScorePowerBonus(),
      challenge1ScorePower: runtime.infiniteAngleScorePower(),
      nextFloor: runtime.towerNextFloor(),
      nextCostLog10: Number(runtime.towerNextFloorCostLog10().toPrecision(6)),
      gate: runtime.towerGateForFloor(runtime.towerNextFloor()),
      canBuild: runtime.canBuildTower(),
      challengeCount: runtime.TOWER_CHALLENGE_COUNT,
      activeChallenge: runtime.state.activeTowerChallenge,
      completedChallenges: runtime.state.completedTowerChallenges,
      challenges: runtime.TOWER_CHALLENGES.map((challenge) => ({
        index: challenge.index,
        name: runtime.towerChallengeName(challenge.index),
        implemented: runtime.towerChallengeImplemented(challenge.index),
        unlocked: runtime.towerChallengeUnlocked(challenge.index),
        completed: runtime.towerChallengeCompleted(challenge.index),
        targetLog10: Number.isFinite(challenge.targetLog10) ? challenge.targetLog10 : null,
      })),
    },
    timeline: {
      discovered: runtime.timelineDiscovered(),
      earnedTf: runtime.timelineEarnedTf(),
      availableTf: runtime.timelineAvailableTf(),
      spentTf: runtime.timelineSpentTf(),
      parallelSecondsSinceIc8Clear: runtime.timelineParallelSecondsSinceIc8Clear(),
      parallelRawLog10: runtime.timelineParallelRawLog10(),
      parallelEffectiveLog10: runtime.timelineParallelEffectiveLog10(),
      ipGainMultiplierLog10: runtime.timelineIpGainMultiplierLog10(),
      realInfinityCountGainMultiplier: runtime.timelineRealInfinityCountGainMultiplier?.() ?? 1,
      claims: {
        score: runtime.timelineTrackClaimCount("score"),
        ip: runtime.timelineTrackClaimCount("ip"),
        eternity: runtime.timelineTrackClaimCount("eternity"),
      },
      nextRequirements: {
        scoreLog10: runtime.timelineScoreRequirementLog10(),
        ipLog10: runtime.timelineIpRequirementLog10(),
        eternity: timelineEternityRequirement?.toString() || null,
      },
      canClaim: {
        score: runtime.canClaimTimelineTf("score"),
        ip: runtime.canClaimTimelineTf("ip"),
        eternity: runtime.canClaimTimelineTf("eternity"),
      },
      nodes: runtime.timelineNodes().map((node) => {
        const availability = runtime.timelineNodeAvailability(node.id);
        return {
          id: node.id,
          era: node.era,
          route: node.route,
          costTF: node.costTF,
          prerequisites: node.prerequisites,
          name: node.name?.[runtime.state.language] || node.name?.en || node.name?.ja || "",
          canPurchase: availability.canPurchase,
          state: availability.state,
          reason: availability.reason,
        };
      }),
      purchasedNodes: runtime.state.timelinePurchasedNodes,
    },
    achievements: {
      unlocked: runtime.achievementCount(),
      total: runtime.ACHIEVEMENT_COUNT,
      gainMultiplier: Number(runtime.achievementGainMultiplier().toFixed(4)),
      vertexGainIncrease: Number(runtime.vertexGainIncrease().toPrecision(6)),
      vertexGainIncreaseLog10: Number(runtime.vertexGainIncreaseLog10().toPrecision(6)),
      mask: runtime.state.achievementMask,
      maskHigh: runtime.state.achievementMaskHigh,
      generationMultiplierReward: runtime.isAchievementUnlocked(3),
      totalPlayTime: Number(runtime.state.totalPlayTime.toFixed(1)),
      noGenerationCoreBoostReached: runtime.state.noGenerationCoreBoostReached,
    },
    settings: {
      showFloatingText: runtime.state.showFloatingText,
      lightEffects: runtime.state.lightEffects,
      showFps: runtime.state.showFps,
      fps: Number(runtime.smoothedFps.toFixed(1)),
      language: runtime.state.language,
      numberFormat: runtime.state.numberFormat,
      timeUnit: runtime.state.timeUnit,
      mainTabPosition: runtime.state.mainTabPosition,
      showTimeFluxQuickBar: runtime.state.showTimeFluxQuickBar,
      hiddenTabs: runtime.normalizeHiddenTabs(runtime.state.hiddenTabs),
      unlockedMainTabs: runtime.normalizeUnlockedMainTabs(runtime.state.unlockedMainTabs),
      activeMainTab: runtime.activeMainTab,
      activeEternitySubtab: runtime.activeEternitySubtab,
      activeInfinitySubtab: runtime.activeInfinitySubtab,
      activeChallengeSubtab: runtime.activeChallengeSubtab,
      activeStatisticsSubtab: runtime.activeStatisticsSubtab,
    },
    automation: {
      unlocked: runtime.normalAutomationUnlocked?.() || false,
      layerUnlocked: runtime.infinityAutomationUnlocked?.() || false,
      infinityUpgradeUnlocked: runtime.infinityUpgradeAutomationUnlocked?.() || false,
      enabled: runtime.state.automationEnabled,
      speed: runtime.state.autoBuySpeed,
      vertex: runtime.state.autoBuyVertex,
      gain: runtime.state.autoBuyGain,
      infinityUpgrades: runtime.state.autoBuyInfinityUpgrades,
      generation: runtime.state.autoRunGeneration,
      generationScoreMultiplierThreshold: runtime.state.autoGenerationScoreMultiplierThreshold,
      generationCostMultiplierThreshold: runtime.state.autoGenerationCostMultiplierThreshold,
      generationMinimumSeconds: runtime.state.autoGenerationMinimumSeconds,
      currentGenerationRunTime: Number(runtime.state.currentGenerationRunTime.toFixed(1)),
      coreBoost: runtime.state.autoRunCoreBoost,
      infinity: runtime.state.autoRunInfinity,
      infinityPointThreshold: runtime.state.autoInfinityPointThreshold,
      infinityPointThresholdLog10: runtime.state.autoInfinityPointThresholdLog10,
    },
    statistics: {
      totalPlayTime: Number(runtime.state.totalPlayTime.toFixed(1)),
      totalRealPlayTime: Number(runtime.state.totalRealPlayTime.toFixed(1)),
      currentInfinityRunTime: Number(runtime.state.currentInfinityRunTime.toFixed(1)),
      currentInfinityRealTime: Number(runtime.state.currentInfinityRealTime.toFixed(1)),
      fastestInfinityTime: runtime.state.fastestInfinityTime > 0 ? Number(runtime.state.fastestInfinityTime.toFixed(1)) : null,
      fastestInfinityRealTime: runtime.state.fastestInfinityRealTime > 0
        ? Number(runtime.state.fastestInfinityRealTime.toFixed(1))
        : null,
      fastestInfinityChallengeTimes: runtime.state.fastestInfinityChallengeTimes,
      fastestTowerChallengeTimes: runtime.state.fastestTowerChallengeTimes,
      lastInfinityRuns: runtime.state.lastInfinityRuns,
      currentEternityRunTime: Number(runtime.state.currentEternityRunTime.toFixed(1)),
      currentEternityRealTime: Number(runtime.state.currentEternityRealTime.toFixed(1)),
      fastestEternityTime: runtime.state.fastestEternityTime > 0 ? Number(runtime.state.fastestEternityTime.toFixed(1)) : null,
      fastestEternityRealTime: runtime.state.fastestEternityRealTime > 0
        ? Number(runtime.state.fastestEternityRealTime.toFixed(1))
        : null,
      lastEternityRuns: runtime.state.lastEternityRuns,
    },
    timeFlux: {
      dormant: true,
      amount: runtime.state.timeFlux,
      capacityLevel: runtime.state.timeFluxCapacityLevel,
      gainLevel: runtime.state.timeFluxGainLevel,
      speed: runtime.state.timeFluxSpeed,
      customSpeed: runtime.state.timeFluxCustomSpeed,
      offlineProgressEnabled: runtime.state.offlineProgressEnabled,
      offlineTickCount: runtime.state.offlineTickCount,
      report: runtime.offlineReport,
    },
  });
}

expose("renderGameToText", () => renderGameToText, (value) => { renderGameToText = value; });

window.render_game_to_text = renderGameToText;
window.advanceTime = (ms) => {
  const steps = Math.max(1, Math.round(ms / (1000 / 60)));
  for (let i = 0; i < steps; i += 1) runtime.advanceOnlineTime(1 / 60);
  runtime.uiUpdateElapsed = 0;
  runtime.updateUi();
  runtime.drawActiveView();
};
window.__angleDebug = {
  runtime,
  state: runtime.state,
  uiUpdateCount: () => runtime.uiUpdateCount,
  addScore: runtime.addScore,
  update: runtime.update,
  buySpeed: runtime.buySpeed,
  runGeneration: runtime.runGeneration,
  runCoreBoost: runtime.runCoreBoost,
  runInfinity: runtime.runInfinity,
  runEternityMilestoneAutomation: runtime.runEternityMilestoneAutomation,
  canEternity: runtime.canEternity,
  performEternity: runtime.performEternity,
  eternityGain: runtime.eternityGain,
  eternityGainLog10: runtime.eternityGainLog10,
  claimTimelineTf: runtime.claimTimelineTf,
  claimScoreTf: runtime.claimScoreTf,
  claimIpTf: runtime.claimIpTf,
  claimEternityTf: runtime.claimEternityTf,
  canClaimTimelineTf: runtime.canClaimTimelineTf,
  timelineEarnedTf: runtime.timelineEarnedTf,
  timelineAvailableTf: runtime.timelineAvailableTf,
  timelineSpentTf: runtime.timelineSpentTf,
  timelineParallelSecondsSinceIc8Clear: runtime.timelineParallelSecondsSinceIc8Clear,
  timelineParallelRawLog10: runtime.timelineParallelRawLog10,
  timelineParallelEffectiveLog10: runtime.timelineParallelEffectiveLog10,
  timelineRealInfinityCountGainMultiplier: runtime.timelineRealInfinityCountGainMultiplier,
  timelineIpGainMultiplierLog10: runtime.timelineIpGainMultiplierLog10,
  advanceTimelineRunTime: runtime.advanceTimelineRunTime,
  timelineNodes: runtime.timelineNodes,
  timelineNodeAvailability: runtime.timelineNodeAvailability,
  canPurchaseTimelineNode: runtime.canPurchaseTimelineNode,
  purchaseTimelineNode: runtime.purchaseTimelineNode,
  respecTimeline: runtime.respecTimeline,
  maybeForceEternity: runtime.maybeForceEternity,
  selectEternityMilestone: runtime.selectEternityMilestone,
  buyInfinityUpgrade: runtime.buyInfinityUpgrade,
  buyAllInfinityUpgrades: runtime.buyAllInfinityUpgrades,
  buyAllUpgrades: runtime.buyAllUpgrades,
  generationRewardFor: runtime.generationRewardFor,
  generationScoreMultiplierEffectLog10: runtime.generationScoreMultiplierEffectLog10,
  unlockInfiniteAngle: runtime.unlockInfiniteAngle,
  buyInfiniteAngleUpgrade: runtime.buyInfiniteAngleUpgrade,
  buyAllInfiniteAngleUpgrades: runtime.buyAllInfiniteAngleUpgrades,
  updateInfiniteAngle: runtime.updateInfiniteAngle,
  toggleInfinityChallenge: runtime.toggleInfinityChallenge,
  breakInfiniteCap: runtime.breakInfiniteCap,
  checkAchievements: runtime.checkAchievements,
  switchMainTab: runtime.switchMainTab,
  switchEternitySubtab: runtime.switchEternitySubtab,
  mainTabIsUnlocked: runtime.mainTabIsUnlocked,
  mainTabIsVisible: runtime.mainTabIsVisible,
  setMainTabVisibility: runtime.setMainTabVisibility,
  switchInfinitySubtab: runtime.switchInfinitySubtab,
  switchChallengeSubtab: runtime.switchChallengeSubtab,
  switchStatisticsSubtab: runtime.switchStatisticsSubtab,
  buildTower: runtime.buildTower,
  toggleTowerChallenge: runtime.toggleTowerChallenge,
  completeTowerChallengeIfReady: runtime.completeTowerChallengeIfReady,
  applySetting: runtime.applySetting,
  advanceOnlineTime: runtime.advanceOnlineTime,
  processOfflineElapsed: runtime.processOfflineElapsed,
  handleSaveConflict: runtime.handleSaveConflict,
  handleStorageChange: runtime.handleStorageChange,
  saveGame: runtime.saveGame,
  backupCurrentSave: runtime.backupCurrentSave,
  createCheckpoint: runtime.createCheckpoint,
  recoveryEntries: runtime.recoveryEntries,
  restorePreImportSave: runtime.restorePreImportSave,
  restoreCheckpoint: runtime.restoreCheckpoint,
  restoreUndoSave: runtime.restoreUndoSave,
  retryLoad: runtime.retryLoad,
  restoreQuarantineSave: runtime.restoreQuarantineSave,
  loadGame: runtime.loadGame,
  resetSave: runtime.resetSave,
  exportSaveCode: runtime.exportSaveCode,
  importSaveCode: runtime.importSaveCode,
  syncServerClock: runtime.syncServerClock,
  offlineElapsedFromSave: runtime.offlineElapsedFromSave,
  renderQualityState: runtime.renderQualityState,
  setRenderQualityForTest: runtime.setRenderQualityForTest,
  updateRenderQualityForTest: runtime.updateRenderQualityForTest,
  canvasCacheStats: runtime.canvasCacheStats,
  serverClockAvailable: runtime.serverClockAvailable,
  serverClockNowMs: runtime.serverClockNowMs,
  serverClockSource: () => runtime.serverClockSource,
  ready: null,
};
