import { runtime, expose } from "../runtime/shared.js";

// DOM bindings are evaluated before the runtime composition root.

const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");
const infiniteAngleCanvas = document.getElementById("infiniteAngleCanvas");
const infiniteAngleCtx = infiniteAngleCanvas ? infiniteAngleCanvas.getContext("2d") : null;

const elements = {
  shell: document.getElementById("shell"),
  infiniteAngleCanvas,
  infiniteAngleCtx,
  newsTicker: document.getElementById("newsTicker"),
  newsTickerText: document.getElementById("newsTickerText"),
  timeFluxQuickBar: document.getElementById("timeFluxQuickBar"),
  timeFluxQuickAmount: document.getElementById("timeFluxQuickAmount"),
  timeFluxQuickSpeed: document.getElementById("timeFluxQuickSpeed"),
  timeFluxQuickCustomSpeedInput: document.getElementById("timeFluxQuickCustomSpeedInput"),
  mainTabs: Array.from(document.querySelectorAll(".main-tab")),
  mainPanels: Array.from(document.querySelectorAll(".main-panel")),
  infinitySubtabs: Array.from(document.querySelectorAll(".infinity-subtab")),
  infinitySubpanels: Array.from(document.querySelectorAll(".infinity-subpanel")),
  challengeSubtabs: Array.from(document.querySelectorAll(".challenge-subtab")),
  challengeSubpanels: Array.from(document.querySelectorAll(".challenge-subpanel")),
  timeFluxPanel: document.getElementById("timeFluxPanel"),
  timeFluxAmount: document.getElementById("timeFluxAmount"),
  timeFluxGain: document.getElementById("timeFluxGain"),
  timeFluxSpeed: document.getElementById("timeFluxSpeed"),
  timeFluxOfflineStatus: document.getElementById("timeFluxOfflineStatus"),
  timeFluxOfflineToggle: document.getElementById("timeFluxOfflineToggle"),
  timeFluxTickInput: document.getElementById("timeFluxTickInput"),
  timeFluxCustomSpeedInput: document.getElementById("timeFluxCustomSpeedInput"),
  timeFluxSpeedButtons: Array.from(document.querySelectorAll(".time-flux-speed")),
  timeFluxGainUpgrade: document.getElementById("timeFluxGainUpgrade"),
  timeFluxCapacityUpgrade: document.getElementById("timeFluxCapacityUpgrade"),
  timeFluxGainLevel: document.getElementById("timeFluxGainLevel"),
  timeFluxCapacityLevel: document.getElementById("timeFluxCapacityLevel"),
  timeFluxGainEffect: document.getElementById("timeFluxGainEffect"),
  timeFluxCapacityEffect: document.getElementById("timeFluxCapacityEffect"),
  timeFluxGainCost: document.getElementById("timeFluxGainCost"),
  timeFluxCapacityCost: document.getElementById("timeFluxCapacityCost"),
  offlineReportPanel: document.getElementById("offlineReportPanel"),
  offlineReportMode: document.getElementById("offlineReportMode"),
  offlineReportElapsed: document.getElementById("offlineReportElapsed"),
  offlineReportEffective: document.getElementById("offlineReportEffective"),
  offlineReportTicks: document.getElementById("offlineReportTicks"),
  offlineReportTimeFlux: document.getElementById("offlineReportTimeFlux"),
  offlineReportInfinity: document.getElementById("offlineReportInfinity"),
  offlineReportIp: document.getElementById("offlineReportIp"),
  offlineReportNote: document.getElementById("offlineReportNote"),
  offlineReportClose: document.getElementById("offlineReportClose"),
  scoreValue: document.getElementById("scoreValue"),
  gainValue: document.getElementById("gainValue"),
  vertexGainValue: document.getElementById("vertexGainValue"),
  lapValue: document.getElementById("lapValue"),
  lapSpeedValue: document.getElementById("lapSpeedValue"),
  generationCount: document.getElementById("generationCount"),
  previousGenerationScore: document.getElementById("previousGenerationScore"),
  generationMultiplier: document.getElementById("generationMultiplier"),
  generationCostFactor: document.getElementById("generationCostFactor"),
  generationButton: document.getElementById("generationButton"),
  coreBoostCount: document.getElementById("coreBoostCount"),
  coreBoostRequirement: document.getElementById("coreBoostRequirement"),
  coreBoostGainBoost: document.getElementById("coreBoostGainBoost"),
  coreBoostExponent: document.getElementById("coreBoostExponent"),
  coreBoostButton: document.getElementById("coreBoostButton"),
  infinityCount: document.getElementById("infinityCount"),
  infinityPoints: document.getElementById("infinityPoints"),
  infiniteScore: document.getElementById("infiniteScore"),
  infiniteScorePanel: document.getElementById("infiniteScorePanel"),
  infiniteAngleBoost: document.getElementById("infiniteAngleBoost"),
  infiniteAngleBoostPanel: document.getElementById("infiniteAngleBoostPanel"),
  infiniteAngleUnlockNote: document.getElementById("infiniteAngleUnlockNote"),
  infiniteAngleUnlockButton: document.getElementById("infiniteAngleUnlockButton"),
  infiniteAngleUnlockCost: document.getElementById("infiniteAngleUnlockCost"),
  infiniteAngleVertexCount: document.getElementById("infiniteAngleVertexCount"),
  infiniteAngleCurrentGain: document.getElementById("infiniteAngleCurrentGain"),
  infiniteAngleLap: document.getElementById("infiniteAngleLap"),
  infiniteAngleSpeedUpgrade: document.getElementById("infiniteAngleSpeedUpgrade"),
  infiniteAngleVertexUpgrade: document.getElementById("infiniteAngleVertexUpgrade"),
  infiniteAngleGainUpgrade: document.getElementById("infiniteAngleGainUpgrade"),
  infiniteAngleSpeedLevel: document.getElementById("infiniteAngleSpeedLevel"),
  infiniteAngleVertexLevel: document.getElementById("infiniteAngleVertexLevel"),
  infiniteAngleGainLevel: document.getElementById("infiniteAngleGainLevel"),
  infiniteAngleSpeedCost: document.getElementById("infiniteAngleSpeedCost"),
  infiniteAngleVertexCost: document.getElementById("infiniteAngleVertexCost"),
  infiniteAngleGainCost: document.getElementById("infiniteAngleGainCost"),
  infinityPointGain: document.getElementById("infinityPointGain"),
  infinityButton: document.getElementById("infinityButton"),
  infinityUpgradeTree: document.getElementById("infinityUpgradeTree"),
  infinityUpgradeDetailName: document.getElementById("infinityUpgradeDetailName"),
  infinityUpgradeDetailState: document.getElementById("infinityUpgradeDetailState"),
  infinityUpgradeDetailEffect: document.getElementById("infinityUpgradeDetailEffect"),
  infinityUpgradeDetailRequires: document.getElementById("infinityUpgradeDetailRequires"),
  infinityUpgradeDetailCost: document.getElementById("infinityUpgradeDetailCost"),
  infinityUpgradeDetailBuy: document.getElementById("infinityUpgradeDetailBuy"),
  challengeList: document.getElementById("challengeList"),
  challengeStatus: document.getElementById("challengeStatus"),
  towerChallengeList: document.getElementById("towerChallengeList"),
  towerFloorHeading: document.getElementById("towerFloorHeading"),
  towerFloorValue: document.getElementById("towerFloorValue"),
  towerScoreExponentValue: document.getElementById("towerScoreExponentValue"),
  towerNextCost: document.getElementById("towerNextCost"),
  towerGateStatus: document.getElementById("towerGateStatus"),
  towerBuildButton: document.getElementById("towerBuildButton"),
  breakCapRequirement: document.getElementById("breakCapRequirement"),
  breakCapButton: document.getElementById("breakCapButton"),
  achievementList: document.getElementById("achievementList"),
  achievementSummary: document.getElementById("achievementSummary"),
  achievementBoost: document.getElementById("achievementBoost"),
  achievementTabState: document.getElementById("achievementTabState"),
  achievementToasts: document.getElementById("achievementToasts"),
  buyAllUpgrade: document.getElementById("buyAllUpgrade"),
  speedUpgrade: document.getElementById("speedUpgrade"),
  vertexUpgrade: document.getElementById("vertexUpgrade"),
  gainUpgrade: document.getElementById("gainUpgrade"),
  saveStatus: document.getElementById("saveStatus"),
  resetSaveButton: document.getElementById("resetSaveButton"),
  speedLevel: document.getElementById("speedLevel"),
  vertexCount: document.getElementById("vertexCount"),
  gainLevel: document.getElementById("gainLevel"),
  speedCost: document.getElementById("speedCost"),
  vertexCost: document.getElementById("vertexCost"),
  gainCost: document.getElementById("gainCost"),
  floatingTextToggle: document.getElementById("floatingTextToggle"),
  lightEffectsToggle: document.getElementById("lightEffectsToggle"),
  fpsToggle: document.getElementById("fpsToggle"),
  fpsCounter: document.getElementById("fpsCounter"),
  languageSelect: document.getElementById("languageSelect"),
  numberFormatSelect: document.getElementById("numberFormatSelect"),
  timeUnitSelect: document.getElementById("timeUnitSelect"),
  topBarModeSelect: document.getElementById("topBarModeSelect"),
  timeFluxQuickBarToggle: document.getElementById("timeFluxQuickBarToggle"),
  updateModal: document.getElementById("updateModal"),
  updateModalClose: document.getElementById("updateModalClose"),
  i18nNodes: Array.from(document.querySelectorAll("[data-i18n]")),
  infinityTabState: document.getElementById("infinityTabState"),
  infinityTabBadge: document.getElementById("infinityTabBadge"),
  challengeTabState: document.getElementById("challengeTabState"),
  infinityUnlockNote: document.getElementById("infinityUnlockNote"),
  automationMasterToggle: document.getElementById("automationMasterToggle"),
  autoBuySpeedToggle: document.getElementById("autoBuySpeedToggle"),
  autoBuyVertexToggle: document.getElementById("autoBuyVertexToggle"),
  autoBuyGainToggle: document.getElementById("autoBuyGainToggle"),
  autoCompleteChallengesToggle: document.getElementById("autoCompleteChallengesToggle"),
  autoRunGenerationToggle: document.getElementById("autoRunGenerationToggle"),
  autoGenerationScoreThresholdInput: document.getElementById("autoGenerationScoreThresholdInput"),
  autoGenerationCostThresholdInput: document.getElementById("autoGenerationCostThresholdInput"),
  autoGenerationMinimumSecondsInput: document.getElementById("autoGenerationMinimumSecondsInput"),
  autoRunCoreBoostToggle: document.getElementById("autoRunCoreBoostToggle"),
  autoRunInfinityToggle: document.getElementById("autoRunInfinityToggle"),
  autoInfinityPointThresholdInput: document.getElementById("autoInfinityPointThresholdInput"),
  automationLockNote: document.getElementById("automationLockNote"),
  currentInfinityRunTime: document.getElementById("currentInfinityRunTime"),
  totalPlayTime: document.getElementById("totalPlayTime"),
  fastestInfinityTime: document.getElementById("fastestInfinityTime"),
  lastInfinityRuns: document.getElementById("lastInfinityRuns"),
  saveCodeArea: document.getElementById("saveCodeArea"),
  exportSaveCodeButton: document.getElementById("exportSaveCodeButton"),
  importSaveCodeButton: document.getElementById("importSaveCodeButton"),
  copySaveCodeButton: document.getElementById("copySaveCodeButton"),
};

expose("canvas", () => canvas);
expose("ctx", () => ctx);
expose("infiniteAngleCanvas", () => infiniteAngleCanvas);
expose("infiniteAngleCtx", () => infiniteAngleCtx);
expose("elements", () => elements);
