import { runtime, expose } from "../runtime/shared.js";

// Extracted mechanically from the next-runtime baseline.
// DOM bindings are evaluated before the runtime composition root.

const canvas = document.getElementById("gameCanvas");
const ctx = canvas.getContext("2d");

const elements = {
  mainTabs: Array.from(document.querySelectorAll(".main-tab")),
  mainPanels: Array.from(document.querySelectorAll(".main-panel")),
  infinitySubtabs: Array.from(document.querySelectorAll(".infinity-subtab")),
  infinitySubpanels: Array.from(document.querySelectorAll(".infinity-subpanel")),
  scoreValue: document.getElementById("scoreValue"),
  gainValue: document.getElementById("gainValue"),
  vertexGainValue: document.getElementById("vertexGainValue"),
  lapValue: document.getElementById("lapValue"),
  lapSpeedValue: document.getElementById("lapSpeedValue"),
  generationStatus: document.getElementById("generationStatus"),
  generationCount: document.getElementById("generationCount"),
  generationMultiplier: document.getElementById("generationMultiplier"),
  generationCostFactor: document.getElementById("generationCostFactor"),
  generationButton: document.getElementById("generationButton"),
  coreBoostCount: document.getElementById("coreBoostCount"),
  coreBoostRequirement: document.getElementById("coreBoostRequirement"),
  coreBoostGainBoost: document.getElementById("coreBoostGainBoost"),
  coreBoostExponent: document.getElementById("coreBoostExponent"),
  coreBoostButton: document.getElementById("coreBoostButton"),
  infinityCount: document.getElementById("infinityCount"),
  infinityPoints: document.getElementById("infinityPoints"),
  infiniteScore: document.getElementById("infiniteScore"),
  infiniteScorePanel: document.getElementById("infiniteScorePanel"),
  infiniteAngleBoost: document.getElementById("infiniteAngleBoost"),
  infiniteAngleBoostPanel: document.getElementById("infiniteAngleBoostPanel"),
  infinityPointGain: document.getElementById("infinityPointGain"),
  infinityButton: document.getElementById("infinityButton"),
  infinityUpgradeTree: document.getElementById("infinityUpgradeTree"),
  infinityUpgradeDetailName: document.getElementById("infinityUpgradeDetailName"),
  infinityUpgradeDetailState: document.getElementById("infinityUpgradeDetailState"),
  infinityUpgradeDetailEffect: document.getElementById("infinityUpgradeDetailEffect"),
  infinityUpgradeDetailRequires: document.getElementById("infinityUpgradeDetailRequires"),
  infinityUpgradeDetailCost: document.getElementById("infinityUpgradeDetailCost"),
  infinityUpgradeDetailBuy: document.getElementById("infinityUpgradeDetailBuy"),
  convertIpButton: document.getElementById("convertIpButton"),
  convertIpGain: document.getElementById("convertIpGain"),
  challengeList: document.getElementById("challengeList"),
  challengeStatus: document.getElementById("challengeStatus"),
  breakCapButton: document.getElementById("breakCapButton"),
  achievementList: document.getElementById("achievementList"),
  achievementSummary: document.getElementById("achievementSummary"),
  achievementBoost: document.getElementById("achievementBoost"),
  achievementTabState: document.getElementById("achievementTabState"),
  achievementToasts: document.getElementById("achievementToasts"),
  buyAllUpgrade: document.getElementById("buyAllUpgrade"),
  speedUpgrade: document.getElementById("speedUpgrade"),
  vertexUpgrade: document.getElementById("vertexUpgrade"),
  gainUpgrade: document.getElementById("gainUpgrade"),
  saveStatus: document.getElementById("saveStatus"),
  resetSaveButton: document.getElementById("resetSaveButton"),
  speedLevel: document.getElementById("speedLevel"),
  vertexCount: document.getElementById("vertexCount"),
  gainLevel: document.getElementById("gainLevel"),
  speedCost: document.getElementById("speedCost"),
  vertexCost: document.getElementById("vertexCost"),
  gainCost: document.getElementById("gainCost"),
  floatingTextToggle: document.getElementById("floatingTextToggle"),
  lightEffectsToggle: document.getElementById("lightEffectsToggle"),
  fpsToggle: document.getElementById("fpsToggle"),
  fpsCounter: document.getElementById("fpsCounter"),
  languageSelect: document.getElementById("languageSelect"),
  numberFormatSelect: document.getElementById("numberFormatSelect"),
  timeUnitSelect: document.getElementById("timeUnitSelect"),
  updateModal: document.getElementById("updateModal"),
  updateModalClose: document.getElementById("updateModalClose"),
  i18nNodes: Array.from(document.querySelectorAll("[data-i18n]")),
  infinityTabState: document.getElementById("infinityTabState"),
  infinityTabBadge: document.getElementById("infinityTabBadge"),
  infinityUnlockNote: document.getElementById("infinityUnlockNote"),
  automationMasterToggle: document.getElementById("automationMasterToggle"),
  autoBuySpeedToggle: document.getElementById("autoBuySpeedToggle"),
  autoBuyVertexToggle: document.getElementById("autoBuyVertexToggle"),
  autoBuyGainToggle: document.getElementById("autoBuyGainToggle"),
  autoCompleteChallengesToggle: document.getElementById("autoCompleteChallengesToggle"),
  automationLockNote: document.getElementById("automationLockNote"),
  currentInfinityRunTime: document.getElementById("currentInfinityRunTime"),
  totalPlayTime: document.getElementById("totalPlayTime"),
  fastestInfinityTime: document.getElementById("fastestInfinityTime"),
  lastInfinityRuns: document.getElementById("lastInfinityRuns"),
  saveCodeArea: document.getElementById("saveCodeArea"),
  exportSaveCodeButton: document.getElementById("exportSaveCodeButton"),
  importSaveCodeButton: document.getElementById("importSaveCodeButton"),
  copySaveCodeButton: document.getElementById("copySaveCodeButton"),
};



expose("canvas", () => canvas);
expose("ctx", () => ctx);
expose("elements", () => elements);

