import { runtime, expose } from "../runtime/shared.js";

// Extracted mechanically from the next-runtime baseline. Keep declaration order stable during migration.

const BASE_LAP_SECONDS = 6;
const GENERATION_UNLOCK_SCORE = 1000000;
const GENERATION_MIN_NEW_COST_FACTOR = 0.78;
const CORE_BOOST_BASE_REQUIREMENT = 1e20;
const INFINITY_REQUIREMENT_LOG10 = 308 + Math.log10(1.8);
const BREAK_CAP_REQUIREMENT_LOG10 = 350;
const MAX_TRACKED_LOG10 = 1000000000;
const MAX_RENDERED_VERTICES = 10000;
const LAP_SPEED_SUPER_SOFTCAP_START_LOG10 = 22;
const LAP_SPEED_SUPER_SOFTCAP_LOG_STRENGTH = 0.25;
const INFINITY_CHALLENGE_COUNT = 8;
const ACHIEVEMENT_COUNT = 25;
const SAVE_KEY = "angle-incremental-save";
const SAVE_QUARANTINE_KEY = "angle-incremental-save-quarantine";
const SAVE_VERSION = 7;
const APP_VERSION = "0.1.0";
const SAVE_CODE_PREFIX = "ANGLE_SAVE_V2:";
const SAVE_CODE_SALT = "angle-incremental-save-code-v2";
const SAVE_CODE_SECRET = "Angle Incremental local save code obfuscation";
const UPDATE_SEEN_KEY = "angle-incremental-seen-version";
const UPDATE_RELOAD_TARGET_KEY = "angle-incremental-update-reload-target";
const UPDATE_RELOAD_TIME_KEY = "angle-incremental-update-reload-time";
const UPDATE_DEFERRED_TARGET_KEY = "angle-incremental-update-deferred-target";
const VERSION_MANIFEST_URL = "version.json";
const UPDATE_CHECK_INTERVAL_SECONDS = 60;
const UPDATE_RETRY_COOLDOWN_MS = 10 * 60 * 1000;
const UI_UPDATE_INTERVAL_SECONDS = 0.1;
const MAX_SIMULATION_STEP_SECONDS = 1 / 30;
const MAX_VERTEX_STEPS_PER_FRAME = 5000;
const MAX_EXACT_CORE_HITS = 50000;
const CORE_HIT_APPROX_SEGMENTS = 2048;
const LAP_SPEED_SOFTCAP_START = 200;
const LAP_SPEED_SOFTCAP_POWER = 0.5;
const PRE_GENERATION_LAP_SPEED_SOFTCAP_START = 35;
const PRE_GENERATION_LAP_SPEED_SOFTCAP_POWER = 0.22;
const PRE_GENERATION_COST_SCALING = {
  speed: { startsAfter: 20, logScale: 0.3 },
  vertex: { startsAfter: 15, logScale: 1.2 },
  gain: { startsAfter: 12, logScale: 0.55 },
};
const STAGED_UPGRADE_COST_SCALING = [
  { startsAfterLog10: 30, logScale: 0.02 },
  { startsAfterLog10: 100, logScale: 0.006 },
];
const INFINITE_ANGLE_CONVERSION_COST_LOG10 = 20;
const GENERATION_SCORE_POWER = 2;
const GENERATION_SCORE_POWER_IC3_REWARD = 2.1;
const GENERATION_COST_POWER_IC3_REWARD = 1.08;
const VERTEX_EPSILON = 1e-9;
const TAU = Math.PI * 2;
const BUY_ALL_LIMIT = 1000;
const AUTOBUY_INTERVAL_SECONDS = 0.1;
const MAX_VERTEX_PROGRESS_TRACKED = 1000000000000;
expose("BASE_LAP_SECONDS", () => BASE_LAP_SECONDS);
expose("GENERATION_UNLOCK_SCORE", () => GENERATION_UNLOCK_SCORE);
expose("GENERATION_MIN_NEW_COST_FACTOR", () => GENERATION_MIN_NEW_COST_FACTOR);
expose("CORE_BOOST_BASE_REQUIREMENT", () => CORE_BOOST_BASE_REQUIREMENT);
expose("INFINITY_REQUIREMENT_LOG10", () => INFINITY_REQUIREMENT_LOG10);
expose("BREAK_CAP_REQUIREMENT_LOG10", () => BREAK_CAP_REQUIREMENT_LOG10);
expose("MAX_TRACKED_LOG10", () => MAX_TRACKED_LOG10);
expose("MAX_RENDERED_VERTICES", () => MAX_RENDERED_VERTICES);
expose("MAX_DRAW_VERTICES", () => MAX_DRAW_VERTICES);
expose("LAP_SPEED_SUPER_SOFTCAP_START_LOG10", () => LAP_SPEED_SUPER_SOFTCAP_START_LOG10);
expose("LAP_SPEED_SUPER_SOFTCAP_LOG_STRENGTH", () => LAP_SPEED_SUPER_SOFTCAP_LOG_STRENGTH);
expose("INFINITY_CHALLENGE_COUNT", () => INFINITY_CHALLENGE_COUNT);
expose("ACHIEVEMENT_COUNT", () => ACHIEVEMENT_COUNT);
expose("SAVE_KEY", () => SAVE_KEY);
expose("SAVE_QUARANTINE_KEY", () => SAVE_QUARANTINE_KEY);
expose("SAVE_VERSION", () => SAVE_VERSION);
expose("APP_VERSION", () => APP_VERSION);
expose("SAVE_CODE_PREFIX", () => SAVE_CODE_PREFIX);
expose("SAVE_CODE_SALT", () => SAVE_CODE_SALT);
expose("SAVE_CODE_SECRET", () => SAVE_CODE_SECRET);
expose("UPDATE_SEEN_KEY", () => UPDATE_SEEN_KEY);
expose("UPDATE_RELOAD_TARGET_KEY", () => UPDATE_RELOAD_TARGET_KEY);
expose("UPDATE_RELOAD_TIME_KEY", () => UPDATE_RELOAD_TIME_KEY);
expose("UPDATE_DEFERRED_TARGET_KEY", () => UPDATE_DEFERRED_TARGET_KEY);
expose("VERSION_MANIFEST_URL", () => VERSION_MANIFEST_URL);
expose("UPDATE_CHECK_INTERVAL_SECONDS", () => UPDATE_CHECK_INTERVAL_SECONDS);
expose("UPDATE_RETRY_COOLDOWN_MS", () => UPDATE_RETRY_COOLDOWN_MS);
expose("UI_UPDATE_INTERVAL_SECONDS", () => UI_UPDATE_INTERVAL_SECONDS);
expose("MAX_SIMULATION_STEP_SECONDS", () => MAX_SIMULATION_STEP_SECONDS);
expose("MAX_VERTEX_STEPS_PER_FRAME", () => MAX_VERTEX_STEPS_PER_FRAME);
expose("MAX_EXACT_CORE_HITS", () => MAX_EXACT_CORE_HITS);
expose("CORE_HIT_APPROX_SEGMENTS", () => CORE_HIT_APPROX_SEGMENTS);
expose("LAP_SPEED_SOFTCAP_START", () => LAP_SPEED_SOFTCAP_START);
expose("LAP_SPEED_SOFTCAP_POWER", () => LAP_SPEED_SOFTCAP_POWER);
expose("PRE_GENERATION_LAP_SPEED_SOFTCAP_START", () => PRE_GENERATION_LAP_SPEED_SOFTCAP_START);
expose("PRE_GENERATION_LAP_SPEED_SOFTCAP_POWER", () => PRE_GENERATION_LAP_SPEED_SOFTCAP_POWER);
expose("PRE_GENERATION_COST_SCALING", () => PRE_GENERATION_COST_SCALING);
expose("STAGED_UPGRADE_COST_SCALING", () => STAGED_UPGRADE_COST_SCALING);
expose("INFINITE_ANGLE_CONVERSION_COST_LOG10", () => INFINITE_ANGLE_CONVERSION_COST_LOG10);
expose("GENERATION_SCORE_POWER", () => GENERATION_SCORE_POWER);
expose("GENERATION_SCORE_POWER_IC3_REWARD", () => GENERATION_SCORE_POWER_IC3_REWARD);
expose("GENERATION_COST_POWER_IC3_REWARD", () => GENERATION_COST_POWER_IC3_REWARD);
expose("VERTEX_EPSILON", () => VERTEX_EPSILON);
expose("TAU", () => TAU);
expose("BUY_ALL_LIMIT", () => BUY_ALL_LIMIT);
expose("AUTOBUY_INTERVAL_SECONDS", () => AUTOBUY_INTERVAL_SECONDS);
expose("MAX_VERTEX_PROGRESS_TRACKED", () => MAX_VERTEX_PROGRESS_TRACKED);
