import { runtime, expose } from "../runtime/shared.js";

// Mutable game state and the serialized-field schema.

const MAIN_TAB_IDS = Object.freeze([
  "angle",
  "infinity",
  "eternity",
  "timeline",
  "challenges",
  "automation",
  "statistics",
  "achievements",
  "help",
  "settings",
]);

const MAIN_TAB_DISCOVERY_IDS = Object.freeze([
  "infinity",
  "challenges",
  "automation",
  "eternity",
  "timeline",
]);

function normalizeHiddenTabs(value) {
  if (!Array.isArray(value)) return [];
  return [...new Set(value.filter((tab) => MAIN_TAB_IDS.includes(tab) && tab !== "settings"))];
}

function normalizeUnlockedMainTabs(value) {
  const source = new Set(Array.isArray(value) ? value : []);
  return MAIN_TAB_DISCOVERY_IDS.filter((tab) => source.has(tab));
}

function markMainTabsUnlocked(tabs) {
  const current = normalizeUnlockedMainTabs(state.unlockedMainTabs);
  const next = normalizeUnlockedMainTabs([
    ...current,
    ...(Array.isArray(tabs) ? tabs : [tabs]),
  ]);
  if (next.length === current.length && next.every((tab, index) => tab === current[index])) return false;
  state.unlockedMainTabs = next;
  return true;
}

const state = {
  score: 0,
  scoreLog10: -Infinity,
  totalScore: 0,
  totalScoreLog10: -Infinity,
  generationScore: 0,
  generationScoreLog10: -Infinity,
  vertices: 3,
  ic8VertexUpgradeLevel: 0,
  speedLevel: 0,
  gainLevel: 0,
  currentGain: 1,
  currentGainLog10: 0,
  pointProgress: 0,
  totalVertexProgress: 0,
  lastVertexIndex: 0,
  generationCount: 0,
  previousGenerationScore: 0,
  previousGenerationScoreLog10: -Infinity,
  generationScoreMultiplier: 1,
  generationScoreMultiplierLog10: 0,
  generationCostFactor: 1,
  coreBoostCount: 0,
  infinityCount: 0,
  eternityCount: 0,
  scoreTfClaims: 0,
  ipTfClaims: 0,
  eternityTfClaims: 0,
  timelinePurchasedNodes: [],
  eternityMilestoneMask: 0,
  eternityMilestoneChoice: "",
  infinityPoints: 0,
  infinityPointsLog10: -Infinity,
  infinityPointsExact: "0",
  infiniteScore: 0,
  infiniteScoreLog10: -Infinity,
  infiniteAngleUnlocked: false,
  infiniteAngleSpeedLevel: 0,
  infiniteAngleVertexLevel: 0,
  infiniteAngleGainLevel: 0,
  infiniteAngleCurrentGain: 1,
  infiniteAngleCurrentGainLog10: 0,
  infiniteAnglePointProgress: 0,
  infiniteAngleTotalVertexProgress: 0,
  infiniteAngleLastVertexIndex: 0,
  towerFloor: 0,
  infinityUpgradeMask: 0,
  ipGainUpgradeLevel: 0,
  infiniteAngleUpgradeLevel: 0,
  softcapUpgradeLevel: 0,
  activeChallenge: 0,
  completedChallenges: 0,
  activeChallengeTime: 0,
  activeTowerChallenge: 0,
  completedTowerChallenges: 0,
  activeTowerChallengeTime: 0,
  tc4BaseGainLevel: 0,
  tc4BaseGainPriceStep: 0,
  tc4InfinityScoreVertexGainLevel: 0,
  tc4InfinityScoreVertexGainPriceStep: 0,
  tc4FreeCoreBoostLevel: 0,
  tc4FreeCoreBoostPriceStep: 0,
  fastestInfinityChallengeTimes: Array(8).fill(0),
  fastestTowerChallengeTimes: Array(4).fill(0),
  infiniteCapBroken: false,
  achievementMask: 0,
  achievementMaskHigh: 0,
  totalPlayTime: 0,
  totalRealPlayTime: 0,
  currentInfinityRunTime: 0,
  currentInfinityRealTime: 0,
  fastestInfinityTime: 0,
  fastestInfinityRealTime: 0,
  lastInfinityRuns: [],
  bestInfinityCountPerSecond: 0,
  infinityCountRateRemainder: 0,
  offlineProgressEnabled: true,
  offlineTickCount: 1000,
  timeFlux: 0,
  timeFluxCapacityLevel: 0,
  timeFluxGainLevel: 0,
  timeFluxSpeed: 1,
  timeFluxCustomSpeed: 4,
  automationEnabled: false,
  autoBuySpeed: true,
  autoBuyVertex: true,
  autoBuyGain: true,
  autoBuyInfinityUpgrades: false,
  autoBuyInfiniteAngleSpeed: false,
  autoBuyInfiniteAngleVertex: false,
  autoBuyInfiniteAngleGain: false,
  autoBuildTower: false,
  autoRunGeneration: false,
  autoGenerationScoreMultiplierThreshold: 2,
  autoGenerationCostMultiplierThreshold: 1,
  autoGenerationMinimumSeconds: 0,
  autoGenerationLegacyOrMode: false,
  autoRunCoreBoost: false,
  autoRunInfinity: false,
  autoInfinityPointThreshold: 10,
  autoInfinityPointThresholdLog10: 1,
  currentGenerationRunTime: 0,
  ic8VertexDecayElapsed: 0,
  noGenerationCoreBoostReached: false,
  currentInfinityRunHadGeneration: false,
  currentInfinityRunHadCoreBoost: false,
  showFloatingText: true,
  lightEffects: false,
  showFps: false,
  language: "ja",
  numberFormat: "compact",
  timeUnit: "auto",
  topBarMode: "news",
  showTimeFluxQuickBar: true,
  hiddenTabs: [],
  unlockedMainTabs: [],
  floatingTexts: [],
  lastEarned: 0,
  lastEarnedLog10: -Infinity,
};

const SAVE_FIELDS = [
  "score",
  "scoreLog10",
  "totalScore",
  "totalScoreLog10",
  "generationScore",
  "generationScoreLog10",
  "vertices",
  "ic8VertexUpgradeLevel",
  "speedLevel",
  "gainLevel",
  "currentGain",
  "currentGainLog10",
  "pointProgress",
  "totalVertexProgress",
  "lastVertexIndex",
  "generationCount",
  "previousGenerationScore",
  "previousGenerationScoreLog10",
  "generationScoreMultiplier",
  "generationScoreMultiplierLog10",
  "generationCostFactor",
  "coreBoostCount",
  "infinityCount",
  "eternityCount",
  "scoreTfClaims",
  "ipTfClaims",
  "eternityTfClaims",
  "timelinePurchasedNodes",
  "eternityMilestoneMask",
  "eternityMilestoneChoice",
  "infinityPoints",
  "infinityPointsLog10",
  "infinityPointsExact",
  "infiniteScore",
  "infiniteScoreLog10",
  "infiniteAngleUnlocked",
  "infiniteAngleSpeedLevel",
  "infiniteAngleVertexLevel",
  "infiniteAngleGainLevel",
  "infiniteAngleCurrentGain",
  "infiniteAngleCurrentGainLog10",
  "infiniteAnglePointProgress",
  "infiniteAngleTotalVertexProgress",
  "infiniteAngleLastVertexIndex",
  "towerFloor",
  "infinityUpgradeMask",
  "ipGainUpgradeLevel",
  "infiniteAngleUpgradeLevel",
  "softcapUpgradeLevel",
  "activeChallenge",
  "completedChallenges",
  "activeChallengeTime",
  "activeTowerChallenge",
  "completedTowerChallenges",
  "activeTowerChallengeTime",
  "tc4BaseGainLevel",
  "tc4BaseGainPriceStep",
  "tc4InfinityScoreVertexGainLevel",
  "tc4InfinityScoreVertexGainPriceStep",
  "tc4FreeCoreBoostLevel",
  "tc4FreeCoreBoostPriceStep",
  "fastestInfinityChallengeTimes",
  "fastestTowerChallengeTimes",
  "infiniteCapBroken",
  "achievementMask",
  "achievementMaskHigh",
  "totalPlayTime",
  "totalRealPlayTime",
  "currentInfinityRunTime",
  "currentInfinityRealTime",
  "fastestInfinityTime",
  "fastestInfinityRealTime",
  "lastInfinityRuns",
  "bestInfinityCountPerSecond",
  "infinityCountRateRemainder",
  "offlineProgressEnabled",
  "offlineTickCount",
  "timeFlux",
  "timeFluxCapacityLevel",
  "timeFluxGainLevel",
  "timeFluxSpeed",
  "timeFluxCustomSpeed",
  "automationEnabled",
  "autoBuySpeed",
  "autoBuyVertex",
  "autoBuyGain",
  "autoBuyInfinityUpgrades",
  "autoBuyInfiniteAngleSpeed",
  "autoBuyInfiniteAngleVertex",
  "autoBuyInfiniteAngleGain",
  "autoBuildTower",
  "autoRunGeneration",
  "autoGenerationScoreMultiplierThreshold",
  "autoGenerationCostMultiplierThreshold",
  "autoGenerationMinimumSeconds",
  "autoGenerationLegacyOrMode",
  "autoRunCoreBoost",
  "autoRunInfinity",
  "autoInfinityPointThreshold",
  "autoInfinityPointThresholdLog10",
  "currentGenerationRunTime",
  "ic8VertexDecayElapsed",
  "noGenerationCoreBoostReached",
  "currentInfinityRunHadGeneration",
  "currentInfinityRunHadCoreBoost",
  "showFloatingText",
  "lightEffects",
  "showFps",
  "language",
  "numberFormat",
  "timeUnit",
  "topBarMode",
  "showTimeFluxQuickBar",
  "hiddenTabs",
  "unlockedMainTabs",
  "lastEarned",
  "lastEarnedLog10",
];

function normalizeChoice(value, allowed, fallback) {
  return allowed.includes(value) ? value : fallback;
}
expose("state", () => state);
expose("SAVE_FIELDS", () => SAVE_FIELDS);
expose("MAIN_TAB_IDS", () => MAIN_TAB_IDS);
expose("MAIN_TAB_DISCOVERY_IDS", () => MAIN_TAB_DISCOVERY_IDS);
expose("normalizeHiddenTabs", () => normalizeHiddenTabs);
expose("normalizeUnlockedMainTabs", () => normalizeUnlockedMainTabs);
expose("markMainTabsUnlocked", () => markMainTabsUnlocked);
expose("normalizeChoice", () => normalizeChoice, (value) => { normalizeChoice = value; });
